version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata: